Nukleus transport
reaktivity/nukleus-tcp.spec pull request #17
Opened 2017-08-04 23:42 UTC by cmebarrow

Replaced the Agrona-based streams test scripts with two sets of scripts based on the k3po nukleus transport extension:
1. Low level scripts using the k3po TCP transport (this is a superset of the ones in the original k3po TCP specification)
2. High level scripts (application level)

2017-08-04 23:53 UTC, jfallows requested changes
Please review all scripts for unused `correlationId` property.

2017-08-04 23:53 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/rfc793/client.sent.data.multiple.streams.second.was.reset/client.rpt
> +property correlationId ${nukleus:newCorrelationId()}
Is `correlationId` property still needed?

2017-08-05 00:01 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/rfc793/client.sent.data.multiple.streams.second.was.reset/client.rpt
> +property correlationId ${nukleus:newCorrelationId()}
no, removed ( from all the client scripts)

2017-08-05 00:05 UTC, jfallows approved these changes

2017-08-05 00:05 UTC, merged