Adding more tests
reaktivity/nukleus-tcp.spec pull request #5
Opened 2017-02-07 21:06 UTC by cmebarrow

These will facilitate testing for TCP nukleus issue [#3 Partial writes](https://github.com/reaktivity/nukleus-tcp.java/issues/3)

2017-02-10 06:09 UTC, jfallows requested changes

2017-02-10 06:09 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/client.sent.data.and.close/client/nukleus.rpt
> +#
This scenario should be named `client.sent.data.then.end` instead of `client.sent.data.and.close`.

2017-02-10 06:09 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/server.sent.data.and.close/client/nukleus.rpt
> +#
This scenario should be named `server.sent.data.then.end` instead of `server.sent.data.and.close`.

2017-02-10 06:09 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/server.sent.data.multiple.streams/server/target.rpt
> +property secondStreamWriteReplyFrameType [0x40 0x00 0x00 0x02]
Why is this test parameterized to handle `RESET` or `WINDOW` frame types?
Recommend making the scenario name explicit, and having one or the other or both as needed by ITs.

2017-02-10 06:09 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/server.sent.data/server/target.rpt
>  read [0..4] # TODO: read int 13 option byteorder native
What is the rationale for removing the `close` `closed`?

2017-02-10 06:09 UTC, jfallows commented on src/test/java/org/reaktivity/specification/nukleus/tcp/streams/ClientIT.java
> +    public void shouldReceiveClientSentDataAndClose() throws Exception
Please rename to `shouldReceiveClientSentDataAndEnd`.

2017-02-10 06:09 UTC, jfallows commented on src/test/java/org/reaktivity/specification/nukleus/tcp/streams/ClientIT.java
> +    public void shouldReceiveServerSentDataAndClose() throws Exception
Please rename to `shouldReceiveServerSentDataAndEnd`.

2017-02-10 18:15 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/client.sent.data.and.close/client/nukleus.rpt
> +#
done

2017-02-10 18:15 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/server.sent.data.and.close/client/nukleus.rpt
> +#
done

2017-02-10 18:17 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/server.sent.data.multiple.streams/server/target.rpt
> +property secondStreamWriteReplyFrameType [0x40 0x00 0x00 0x02]
I thought it better not to add a spec script specifically for an implementation detail. But I can certainly do so if you prefer.

2017-02-10 18:18 UTC, cmebarrow commented on src/test/java/org/reaktivity/specification/nukleus/tcp/streams/ClientIT.java
> +    public void shouldReceiveServerSentDataAndClose() throws Exception
done

2017-02-10 18:24 UTC, cmebarrow commented on src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/server.sent.data/server/target.rpt
>  read [0..4] # TODO: read int 13 option byteorder native
Allows the script to be used for a case where the write is done twice (first being a partial write). In this case two window update frames are received. I felt this was a case of over specification. It's perfectly valid to get several window updates.

2017-02-10 18:24 UTC, cmebarrow commented on src/test/java/org/reaktivity/specification/nukleus/tcp/streams/ClientIT.java
> +    public void shouldReceiveServerSentDataAndClose() throws Exception
done

2017-02-10 18:26 UTC, cmebarrow commented on src/test/java/org/reaktivity/specification/nukleus/tcp/streams/ClientIT.java
> +    public void shouldReceiveClientSentDataAndClose() throws Exception
done

2017-02-10 22:03 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/tcp/streams/server.sent.data/server/target.rpt
>  read [0..4] # TODO: read int 13 option byteorder native
Yes, I understand and agree.

There is significant flexibility in the timing and values of window updates in general, which is probably best resolved by adding a `nukleus` stream transport to k3po that handles the flow control internally for the higher level interactions and keep the low level stuff to a handful of tests that actually intend to describe how flow control should behave.

2017-02-10 22:38 UTC, jfallows approved these changes

2017-02-11 02:09 UTC, jfallows approved these changes

2017-02-11 02:10 UTC, merged